### ISSUE TITLE
Ansible problem with dnf

### ISSUE THREAD

**Issue by jogre** [ForgeRock/frstack#21]
Hi Warren,

Tried to install the full lot after the GitHub clone. Works nicely until ansible complains about dnf as the package manager. Is there a setting that I missed to enable dnf ?
[...]
==> joserver: Machine booted and ready!
==> joserver: Checking for guest additions in VM...
==> joserver: Setting hostname...
==> joserver: Configuring and enabling network interfaces...
==> joserver: Mounting shared folders...
    joserver: /vagrant => /Users/joachim/Documents/ForgeRock/01_Tech/08_frstack/frstack/vagrant
==> joserver: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_FORCE_COLOR=true ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --user=vagrant --connection=ssh --timeout=30 --limit='joserver' --inventory-file=/Users/joachim/Documents/ForgeRock/01_Tech/08_frstack/frstack/vagrant/.vagrant/provisioners/ansible/inventory --sudo -v ../ansible/frstack.yml
ERROR: dnf is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Thanks,
Joachim

**Comment by wstrange** [comment]
Hi Joachim

Fedora is switching from yum to dnf - and the current Ansible package manager has issues dealing with both. I thought I worked around this by using a dnf package. but I think I need to revisit the install to work around this issue until Ansible gets a new package module. 

You might try to  s/snf/yum/  and see if that gets around it

I'll keep this open until we get a fix

**Comment by jogre** [comment]
Hi Warren,

It was an ansible version mismatch. On the Mac, "brew install ansible" installed me version 1.8.4; install with pip gives me 1.9.4 where I don't see this issue. For dnf, it needs minimum 1.9 according to ansible forums. A note in the install instructions should be sufficient wrt version.  Please close the ticket.  
Thanks,
Joachim

**Comment by bingoarunprasath** [comment]
Hi Warren / Jogre,

I am also facing the same issue with Ansible 1.9.4 using one of the Openstack cloud-image for centos7.

Probably because of the image. Will need to dig further. 

Thanks,
Arun

**Comment by wstrange** [comment]
Hi Arun

The problem here is that Ansible's 1.9.x support for Fedora / Centos packages is somewhat broken. 

Fedora is in the process of switching to DNF. The current Vagrant image used Fedora / DNF - so it should work on that combination.

Centos is still on rpm - but I gather they are also moving to DNF as well.

Ansible 2.x is supposed to solve this by having a package manager that works on both DNF and rpm. 

I am just waiting for 2.x to ship to convert the project - which should solve this issue for good

Until then I think you will have to edit the .yaml files and install packages via yum (or alternatively - move to a Fedora image..)

**Comment by wstrange** [comment]
Updated to Fedora 23 / Ansible 2.0

Now works
